name: Test Actions

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-action:
    strategy:
      matrix:
        platform:
          - linux/386
          - linux/amd64
          - linux/arm/v6
          - linux/arm/v7 
          - linux/arm64
          - linux/ppc64le
          - linux/riscv64
          - linux/s390x
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build binary
        id: docker-build
        uses: go-cross/docker-actions@v1
        with:
          platforms: ${{ matrix.platform }}
          output: dp

      - name: Print folder tree
        run: sudo apt install tree && tree ./bin

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          logout: true
          username: xhofe
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: xhofe/domain-proxy

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ steps.docker-build.outputs.platforms }}